[package]
name = "moon"
version = "0.1.2"
authors = ["Paul Carleton <paulcarletonjr@gmail.com>"]

[dependencies]
reqwest = "0.8.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
